In [ ]:
"""Code for testing and creating Poincare maps from the numerical 
solutions of the Lorenz system."""

In [2]:
# Importing necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pynamicalsys import ContinuousDynamicalSystem as cds, PlotStyler

In [6]:
cds.available_models()

['lorenz system',
 'henon heiles',
 'rossler system',
 '4d rossler system',
 'duffing']

In [7]:
cds.available_integrators()

['rk4', 'rk45']

In [16]:
ds = cds(model="lorenz system")

In [9]:
ds.info

{'description': '3D Lorenz system',
 'equation': <IPython.core.display.Math object>,
 'equation_readable': "x' = σ(y − x), y' = x(ρ − z) − y, z' = xy − βz",
 'notes': 'Classic Lorenz 1963 model of atmospheric convection. Exhibits chaotic dynamics for some parameter values.',
 'has_jacobian': True,
 'has_variational_equations': True,
 'equations_of_motion': CPUDispatcher(<function lorenz_system at 0x11ca7c680>),
 'jacobian': CPUDispatcher(<function lorenz_jacobian at 0x11ca7c720>),
 'dimension': 3,
 'number_of_parameters': 3,
 'parameters': ['sigma', 'rho', 'beta']}

In [ ]:
total_time = 50
u = [1, 1, 1]
parameters = [10, 28, 8/3]
time_step = 1e-04

In [10]:
total_time = 50
u = [1, 1, 1] # initial condition remain fixed
parameters = [10, 28, 8/3] # A given parameter is alterred
time_step = 1e-04 # time step for numerical integration

In [11]:
ds.integrator("rk4", time_step=time_step)
trajectory = ds.trajectory(u, total_time, parameters=parameters)
trajectory.shape # time, x, y, z

(500000, 4)

In [13]:
print(trajectory)

[[ 1.00000000e-04  1.00000130e+00  1.00259988e+00  9.99833486e-01]
 [ 2.00000000e-04  1.00000520e+00  1.00519952e+00  9.99667276e-01]
 [ 3.00000000e-04  1.00001169e+00  1.00779894e+00  9.99501371e-01]
 ...
 [ 4.99998000e+01 -3.83218294e+00 -1.63003288e+00  2.53014238e+01]
 [ 4.99999000e+01 -3.82998232e+00 -1.63090486e+00  2.52953023e+01]
 [ 5.00000000e+01 -3.82778479e+00 -1.63177849e+00  2.52891823e+01]]


In [ ]:
# To plot the Poincare map the trajecortories will need to be varied by a
# parameter or initial condition. When the solution crosses a given plane
# (e.g. z=25) the (x,y) coordinates will be recorded and plotted.

# Generting a varied set of parameters
varied_param = np.linspace(0, 50, 5)

total_time = 50
u = [1, 1, 1]
time_step = 1e-04

# Adding the varied parameters to the varied parameters
varied_parameters = np.column_stack((
    np.full_like(varied_param, 10, dtype=float),
    varied_param,
    np.full_like(varied_param, 8/3, dtype=float)
))
    
print(varied_parameters.shape)

# Setting the integrator with the chosen time step
ds = cds(model="lorenz system")
ds.integrator("rk4", time_step=time_step)

# Running the trajectories for each parameter set
trajectories = []
for params in varied_parameters:
    traj = ds.trajectory(u, total_time, parameters=params)
    trajectories.append(traj)



(5, 3)
[array([[1.00000000e-04, 9.99999900e-01, 9.99800018e-01, 9.99833346e-01],
       [2.00000000e-04, 9.99999600e-01, 9.99600073e-01, 9.99666716e-01],
       [3.00000000e-04, 9.99999101e-01, 9.99400165e-01, 9.99500110e-01],
       ...,
       [4.99998000e+01, 1.20170536e-22, 1.08153482e-22, 1.94952929e-44],
       [4.99999000e+01, 1.20158519e-22, 1.08142667e-22, 1.94913942e-44],
       [5.00000000e+01, 1.20146504e-22, 1.08131854e-22, 1.94874963e-44]],
      shape=(500000, 4)), array([[1.00000000e-04, 1.00000052e+00, 1.00104996e+00, 9.99833408e-01],
       [2.00000000e-04, 1.00000210e+00, 1.00209982e+00, 9.99666966e-01],
       [3.00000000e-04, 1.00000472e+00, 1.00314961e+00, 9.99500673e-01],
       ...,
       [4.99998000e+01, 5.53774924e+00, 5.53774924e+00, 1.15000000e+01],
       [4.99999000e+01, 5.53774924e+00, 5.53774924e+00, 1.15000000e+01],
       [5.00000000e+01, 5.53774924e+00, 5.53774924e+00, 1.15000000e+01]],
      shape=(500000, 4)), array([[1.00000000e-04, 1.00000115e+00